### ISSUE TITLE
Question on Using D2co-defined  Interest Labels

### ISSUE THREAD

**Issue by justopit** [hyz20/CWM#1]
Hi,

I am curious about the performance of your model when using the  interest labels originally defined by D2co. Could you provide some insights or results on this?

Thank you!

**Comment by hyz20** [comment]
Hi [justopit](https://github.com/justopit),

Thank you very much for your interest in our work. The interest label we defined in [D2Co](https://dl.acm.org/doi/10.1145/3604915.3608797) are

```latex
r_{\mathbf{x}} = \left\{
\begin{aligned}
    & 1,\quad \mathrm{if}~~ (d\leq18s \land w=d) \lor (d>18s \land w>18s) \mathrm{;} \\
    & 0,\quad \mathrm{else;} 
\end{aligned}
\right.
```

And the one we defined similarly in [CWM](http://arxiv.org/abs/2406.07932)

```latex
\begin{split}
    r_{\mathbf{x}} = \left\{
    \begin{aligned}
        & 1,\quad \mathrm{if}~~ (d\leq w_{\text{0.7} \land w=d) \lor (d>w_{\text{0.7} \land w>w_{\text{0.7}) \mathrm{;} \\
        & 0,\quad \mathrm{else;} 
    \end{aligned}
    \right.
\end{split}
```

The only difference between these two definitions is the replacement of $18s$ in D2Co with $w_{0.7}$ in CWM ($w_{0.7}$ means the 70% quantile in watch time). And in both the KuaiRand and WeChat, the $w_{0.7}$ is $17s$, which is similar to the $18s$ we defined in D2Co. 

The $18s$ is the definition of **Long_view** in the original KuaiRand dataset, and they considered this label suitable as an indicator of user interest. However, during the review process of D2Co, we found that some reviewers did not approve of this explicit definition, so we replaced $18s$ with $w_{0.7}$ in CWM.

As you can see, unbiased evaluation of video watching is an open question. The definition of such an interest label that we have adopted may not be perfect either. We are also looking forward to follow-up work to address this open question.
